language: python
python:
  - '3.6'

install: "pip install -r requirements.txt"

before_script:
  - cp .env.example .env

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"


services:
  - postgresql

script:
  - ./manage.py test
