language: python
python:
  - '3.6'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="disquaire_project.settings.travis"

branches:
  only:
    - staging

services:
  - postgresql

script:
  - ./manage.py test
